version: '3.8'
services:
  api:
    build: ./api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=catalog
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - db
      - redis
      
  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - api
      
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    ports:
      - '5432:5432'
      
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
